language: python

sudo: false

env:
    global:
        - TOXENV=''
        - TOXARGS=''
        - TOXPOSARGS=''

matrix:

    include:

        - os: linux
          python: 3.8
          env: TOXENV='test'

before_install:

    # We need a full clone to make sure setuptools_scm
    # works properly
    - git fetch --unshallow .
    - git fetch --depth=1000000

install:
    - pip install tox --upgrade
    - git clone --branch tox-apply-ci-patches git://github.com/astrofrog/ci-helpers.git;
    - source ci-helpers/tox/apply_ci_patches.sh;

script:
    - tox -e $TOXENV $TOXARGS -- $TOXPOSARGS

