language: python

sudo: false

env:
    global:
        - TOXENV=''
        - TOXARGS=''
        - TOXPOSARGS=''

matrix:

    include:

        - os: linux
          python: 3.7
          env: TOXENV='test'

before_install:

    # We need a full clone to make sure setuptools_scm
    # works properly
    - git fetch --unshallow .
    - git fetch --depth=1000000

install:
    - git clone --branch tox-apply-ci-patches git://github.com/astrofrog/ci-helpers.git;

script:
    - source ci-helpers/tox/run_tox.sh;

