variables:
  CIBW_BUILD: cp36-* cp37-*
  CIBW_SKIP: "*-win32 *-manylinux1_i686"
  CIBW_TEST_COMMAND: pytest -p no:warnings --pyargs reproject
  CIBW_TEST_EXTRAS: test

jobs:
- template: azure-template.yml
  parameters:
    targets: [wheels_macosx]
    # targets: [sdist, wheels_linux, wheels_macosx, wheels_windows]
