variables:
  CIBW_BUILD: cp36-* cp37-*
  CIBW_SKIP: "*-win32 *-manylinux1_i686"
  CIBW_TEST_COMMAND: pytest -p no:warnings --pyargs reproject
  CIBW_TEST_EXTRAS: test

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: astrofrog
    name: OpenAstronomy/azure-pipelines-template
    ref: master

jobs:
- template: publish.yml@OpenAstronomy
  parameters:
    targets: [sdist, wheels_linux, wheels_macosx, wheels_windows]
