variables:
  CIBW_BUILD: cp36-* cp37-*
  CIBW_SKIP: "*-win32 *-manylinux1_i686"

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: astrofrog
    name: OpenAstronomy/azure-pipelines-template
    ref: master

jobs:
- template: publish.yml@OpenAstronomy
  parameters:
    test_command: pytest -p no:warnings --pyargs reproject
    test_extras: test
    targets:
    - sdist
    - wheels_linux
    - wheels_macosx
    - wheels_windows
