resources:
  repositories:
  - repository: tox
    type: github
    endpoint: github
    name: tox-dev/azure-pipelines-template
    ref: refs/tags/0.2

jobs:
- template: run-tox-env.yml@tox
  parameters:
    tox_version: 'tox'
    jobs:
      py36-test:
        image: [linux, windows, macOs]
      py37-test:
        image: [linux, windows, macOs]
