variables:
  CIBW_BUILD: cp27-* cp36-* cp37-*
  CIBW_SKIP: "*-win32 *-manylinux1_i686"
  CIBW_TEST_COMMAND: pytest -p no:warnings --pyargs reproject
  CIBW_TEST_REQUIRES:

jobs:
- template: azure-template.yml
