name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      toxargs: -vvv
      posargs: --durations=0
      envs: |
        - macos: py310-test
      libraries: |
        apt:
          - libopenblas-dev
      coverage: 'codecov'
