name: Windows Python 3.13 CI

on:
  push:
  pull_request:

jobs:
  test-windows-py313:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Python version
        run: python --version
      - name: Header
        run: |
          type C:\hostedtoolcache\windows\Python\3.13.4\x64\include\pyconfig.h
        shell: cmd
      - name: Show Py_GIL_DISABLED value
        run: findstr /S /C:"#define Py_GIL_DISABLED" C:\hostedtoolcache\windows\Python\3.13.4\x64\include\*.h
        shell: cmd
